#!/usr/bin/env node
/**
 * Builds shared/geo/slovenia.json from Natural Earth 1:10m (world-atlas, public domain).
 * Output (all coordinates already projected, Mercator):
 *   frames.country  viewBox 1000×H, Slovenia fitted, neighbours clipped to the frame
 *   frames.wide     viewBox 1600×1000, Slovenia centred with regional context
 * Each frame: outline (SVG path), neighbours {name: path}, cities, regions (12 NUTS-3 seeds),
 * dots [[x, y, regionIndex]] on a regular grid inside the border (region = nearest seed),
 * labels for neighbouring countries and the sea.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';
import { geoMercator, geoPath, geoContains } from 'd3-geo';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const topo = JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules/world-atlas/countries-10m.json'), 'utf8'));
const countries = feature(topo, topo.objects.countries);
const byId = (id) => countries.features.find((f) => String(f.id) === id);
const SI = byId('705');
const NEIGHBOURS = { Italija: byId('380'), Avstrija: byId('040'), 'Madžarska': byId('348'), 'Hrvaška': byId('191') };

const CITIES = [
  ['Ljubljana', 14.5058, 46.0569], ['Maribor', 15.6459, 46.5547], ['Celje', 15.2604, 46.2309],
  ['Kranj', 14.3556, 46.2389], ['Koper', 13.7302, 45.5481], ['Novo mesto', 15.1689, 45.8034],
  ['Škofja Loka', 14.3064, 46.1655], ['Velenje', 15.1103, 46.3592], ['Nova Gorica', 13.648, 45.956],
  ['Murska Sobota', 16.1664, 46.6625], ['Ptuj', 15.87, 46.42], ['Kočevje', 14.863, 45.643],
  ['Krško', 15.4917, 45.9589], ['Postojna', 14.2153, 45.7743], ['Slovenj Gradec', 15.0806, 46.5103],
  ['Trbovlje', 15.0536, 46.155], ['Jesenice', 14.0536, 46.4364],
];
// 12 statistical regions (NUTS-3); seeds sit near each region's centre of mass.
const REGIONS = [
  ['SI031', 'Pomurska', 16.13, 46.66], ['SI032', 'Podravska', 15.78, 46.45], ['SI033', 'Koroška', 15.0, 46.55],
  ['SI034', 'Savinjska', 15.3, 46.3], ['SI035', 'Zasavska', 15.0, 46.12], ['SI036', 'Posavska', 15.5, 45.97],
  ['SI037', 'Jugovzhodna Slovenija', 15.05, 45.7], ['SI038', 'Primorsko-notranjska', 14.3, 45.66],
  ['SI041', 'Osrednjeslovenska', 14.6, 46.0], ['SI042', 'Gorenjska', 14.15, 46.36],
  ['SI043', 'Goriška', 13.75, 46.12], ['SI044', 'Obalno-kraška', 13.85, 45.6],
];
const LABELS = [
  ['Italija', 13.2, 46.25], ['Avstrija', 14.7, 46.72], ['Madžarska', 16.55, 46.78],
  ['Hrvaška', 15.35, 45.55], ['Jadransko morje', 13.35, 45.48],
];

const r1 = (n) => Math.round(n * 10) / 10;

function frame(W, H, extent) {
  const projection = geoMercator().fitExtent(extent, SI).clipExtent([[0, 0], [W, H]]);
  const pathGen = geoPath(projection).digits(1);
  const proj = (lon, lat) => projection([lon, lat]).map(r1);
  const neighbours = Object.fromEntries(Object.entries(NEIGHBOURS).map(([n, f]) => [n, pathGen(f)]));
  const regions = REGIONS.map(([id, name, lon, lat]) => { const [x, y] = proj(lon, lat); return { id, name, x, y }; });
  const step = Math.round(W / 72);
  const dots = [];
  for (let y = step / 2; y < H; y += step) {
    for (let x = step / 2; x < W; x += step) {
      const ll = projection.invert([x, y]);
      if (!geoContains(SI, ll)) continue;
      let best = 0, bd = Infinity;
      regions.forEach((r, i) => { const d = (r.x - x) ** 2 + (r.y - y) ** 2; if (d < bd) { bd = d; best = i; } });
      dots.push([r1(x), r1(y), best]);
    }
  }
  return {
    viewBox: [0, 0, W, H],
    dotStep: step,
    outline: pathGen(SI),
    neighbours,
    cities: CITIES.map(([name, lon, lat]) => { const [x, y] = proj(lon, lat); return { name, x, y }; }),
    regions,
    labels: LABELS.map(([name, lon, lat]) => { const [x, y] = proj(lon, lat); return { name, x, y }; }),
    dots,
    projection: { type: 'mercator', scale: r1(projection.scale()), translate: projection.translate().map(r1) },
  };
}

const country = frame(1000, 650, [[24, 24], [976, 626]]);
const wide = frame(1600, 1000, [[430, 230], [1170, 770]]);
const out = { source: 'Natural Earth 1:10m via world-atlas (public domain). Regions approximated by nearest-seed partition.', frames: { country, wide } };
fs.mkdirSync(path.join(ROOT, 'shared/geo'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'shared/geo/slovenia.json'), JSON.stringify(out));
// JS module twin so pages can import without fetch()
fs.writeFileSync(path.join(ROOT, 'shared/geo/slovenia.js'), `// Generated by tools/build-geo.mjs — do not edit.\nwindow.JASNO_GEO = ${JSON.stringify(out)};\n`);

const palette = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#9a6324'];
const c = country;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${c.viewBox[2]} ${c.viewBox[3]}" width="1000" height="${c.viewBox[3]}">
<rect width="100%" height="100%" fill="#f4f6f7"/>
${Object.values(c.neighbours).map((d) => `<path d="${d}" fill="none" stroke="#9aa" stroke-dasharray="3 3"/>`).join('')}
<path d="${c.outline}" fill="#e3ebf1" stroke="#0f1720" stroke-width="1.5"/>
${c.dots.map(([x, y, r]) => `<circle cx="${x}" cy="${y}" r="3.2" fill="${palette[r]}"/>`).join('')}
${c.cities.map((p) => `<circle cx="${p.x}" cy="${p.y}" r="4" fill="#000"/><text x="${p.x + 6}" y="${p.y - 6}" font-size="12" font-family="sans-serif">${p.name}</text>`).join('')}
${c.labels.map((p) => `<text x="${p.x}" y="${p.y}" font-size="14" fill="#678" font-family="sans-serif">${p.name}</text>`).join('')}
</svg>`;
fs.writeFileSync(path.join(ROOT, 'shared/geo/slovenia-preview.svg'), svg);
console.log(`country: ${c.dots.length} dots, outline ${c.outline.length} chars; wide: ${wide.dots.length} dots`);
